name: \[P1\] threads compile

on:
  push:
    branches: [ "main" , "pintos-cicd"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make utils
      run: cd src/utils && make clean && make
      # install qemu
    - name: install qemu
      run: sudo apt-get install qemu
    - name: install pintos
      run: cp bin/pintos/* /usr/local/bin
    # run tests
    - name: test threads
      run: cd src/threads && make check