name: 'Calificación de las fases del proyecto'

on: [push]

jobs:
  threads:
    name: 'Fase: Threads'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Clonando repositorio'
        uses: 'actions/checkout@v2'
      - name: Pintos Checker
        id: phase
        uses: gbenm/pintos-checker@v1
        with:
            phase: "threads" # default
            root: "." # default
            utils_path: "src/utils" # default
            make: "make clean && make && make check" # default
      - name: 'Show results'
        run: 'echo "${{ steps.phase.outputs.results }}"'
